### PR TITLE
Improve documentation for subject and object categories

### PR DESCRIPTION
**Pull request by matentzn**
Solves #256

Resolves [#ISSUE, #ISSUE]

- [ ] `docs/` have been added/updated if necessary
- [ ] `make test` has been run locally
- [ ] tests have been added/updated (if applicable)
- [ ] [CHANGELOG.md](https://github.com/mapping-commons/sssom/blob/0.9.0/CHANGELOG.md) has been updated.

[Description, mentioning at least relevant #ISSUE and how it was addressed. A bulleted list of all changes performed by the PR is is helpful.]

### CODE REVIEW

**Comment by saubin78** [comment]
Thanks, this is much clearer with the category examples in particular. 
Yet, there is still something confusing. As you state that this "is documentation for human reviewers", I suggest that the final example be a term label, e.g. "anatomical entity", instead of an identifier "UBERON:0001062".

**Comment by matentzn** [comment]
@saubin78 thats right, can you check again?

**Comment by saubin78** [comment]
This looks like a good compromise as it allows using a controlled vocabulary or not, a label or a CURIE. 👍

**Comment by matentzn** [comment]
Thank you @saubin78

**Pull request merged**
