### PR TITLE
SSSOM 0.11.1 release

### PR DESCRIPTION
**Pull request by matentzn**
Recreating the SSSOM schema files

### CODE REVIEW

**Comment by matentzn** [comment]
@hrshdhgd can you remind me what needs to happen to run a full release (which make commands to run, PR, github release, documentation update etc), and also document that in here: https://github.com/mapping-commons/sssom/blob/master/src/docs/editors.md?

**Comment by hrshdhgd** [comment]
To run a release, just run it through GitHub Releases. This triggers a workflow to release it to pypi. Documentation is updated automatically after every PR is merged. There is no `make` command needed to do this.

**Comment by hrshdhgd** [comment]
I haven't done this in a while. I think `make deploy` deploys documentation and release is done by the usual GitHub Releases. `make build` and `make pypi` are commands to do the same but GitHub Releases is the preferred way.

**Comment by matentzn** [comment]
> Do you want to save anything in there or nuke it and rewrite the page.

Nuke it and replace by a single standard workflow for making a sssom release! :) Thanks! Can be 3 bullets!

**Comment by hrshdhgd** [comment]
Done

**Comment by matentzn** [comment]
@hrshdhgd thank you so much!

**Pull request merged**
