### PR TITLE
Fix documentation build/deployment Action

### PR DESCRIPTION
**Pull request by sujaypatil96**
- [x] `docs/` have been added/updated if necessary
- [x] `make test` has been run locally
- [x] tests have been added/updated (if applicable)
- [x] [CHANGELOG.md](https://github.com/mapping-commons/sssom/blob/master/CHANGELOG.md) has been updated.

The documentation build Action triggered after merging in PR #333 didn't go through: https://github.com/mapping-commons/sssom/actions/runs/6862846838, and that is because I had forgotten to include the updated pyproject.toml/poetry.lock files in that PR. Merging in this PR will fix that. I also updated the deploy_documentation.yaml workflow to use the Makefile target to build the docs rather than writing out the full commands.

### CODE REVIEW

**Review by matentzn — APPROVED** [review]
LGTM, but lacking some context to truly assess this.

**Comment by matentzn** [comment]
@hrshdhgd can you check this as well?

**Comment by hrshdhgd** [comment]
It looks like 1/4 tasks are complete. Is that true or an oversight. I didn't review it assuming that the PR is incomplete because of that.

**Comment by hrshdhgd** [comment]
Other than that, looks good.

**Comment by sujaypatil96** [comment]
My apologies, I hadn't checked off some of those boxes because they weren't applicable to this PR, but we're good to 🚀

**Pull request merged**
