### PR TITLE
Update SSSOM talks 2022 in docs

### PR DESCRIPTION
**Pull request by matentzn**
Adding all the talks, seminars, etc we participated in last year.

### CODE REVIEW

**Comment by cthoyt** [comment]
What about the prefixes curies and iris workshops?

**Comment by matentzn** [comment]
Do you have a link to the meeting announcement? Was there a recording?

**Comment by cthoyt** [comment]
https://biopragmatics.github.io/workshops/WPCI2021, I forgot in 2022 you were a bit busy and didn't prepare specific slides

**Comment by matentzn** [comment]
Added record. Thanks!

**Pull request merged**
